name: Print Hello World

on: [push]

jobs:
  print_hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Print Hello World Content
      run: cat hello_world.txt
