name: Print Hello World

on:
  push:
    branches:
      - main
      
jobs:
  print_hello_world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print Hello World Content
      run: cat hello_world.txt
